### PR TITLE
Some url fixing

### PR DESCRIPTION
**Pull request by cman131**
I switched the id path to only accept alphanumerics

### CODE REVIEW

**Comment by bbesmanoff** [comment]
What is the purpose of this change?

**Comment by cman131** [comment]
To fix the broken url regex from the previous PR

**Comment by bbesmanoff** [comment]
With that context:

1. Can this be squashed?
2. The description mentions 15-65 characters, but that isn't enforced by the regex.

**Comment by cman131** [comment]
1. I am against squashing this.
2. Yeah, sorry about that when writing the description. I forgot that I had removed the limit. I didn't have a concrete length, so it was scrapped

**Comment by CShapleigh** [comment]
I like it but the character limit needs to be addressed by the team

**Comment by bbesmanoff** [comment]
:+1:

**Pull request merged**
